### ISSUE TITLE
Not record voice_call

### ISSUE THREAD

**Issue by Oleksandrrr** [Asaye/react-native-media-recorder#2]
`const params = {
      audioSource: 'VOICE_CALL',
      outputFolder: 'Music/',
    };
    Audio.prepare(params);
    setTimeout(() => {
      Audio.startRecording(); // to start audio recording.
    }, 1000);`
get error:
`Error: Attempt to invoke virtual method 'android.app.FragmentManager android.app.Activity.getFragmentManager()' on a null object reference`, can you told, what ploblem can be(use different type of audioSource,error the same )?

**Comment by Asaye** [comment]
Most likely, this error is due to an attempt to record an audio file while the app is in the background. Was your app running in the background when you face this problem? If so, try to record the audio file while running your app in the foreground.
